version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysql", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:3.2.8
    hostname: redis
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}
    command:
      --requirepass redis
    ports:
      - 6379:6379

  app:
    build: .
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    container_name: likesoft_test_task
    restart: always
    hostname: web
    volumes:
      - .:/likesoft
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
      - db

    depends_on:
      db:
        condition: service_healthy

  celery-worker:
    restart: always
    build: .
    command: bash -c "
      rm -rf /tmp/celery*.pid &
      python -m celery -A config worker --loglevel=info"
    depends_on:
      - app
      - redis

volumes:
  data: